import type { getExamTimeResponseType } from "@/types/dashboard/exam.types";

export const mockExamTimeResponse: getExamTimeResponseType = {
	RetResponse: {
		ResponseMessage: "Success",
		StatusCode: 200,
		ResponseCode: 0,
		ResponseType: true,
	},
	RetData: [
		{
			exam_room_id: 1,
			room_number: "101",
			num_of_pc: 40,
			assigned_seats: 2,
			total_students: 2,
			students: [
				{
					id: 1,
					stu_id: 1001,
					examinee_number: "31251961",
					first_name: "Тунгалаг",
					last_name: "Алтангэрэл",
					register_number: "ФД07292729",
					gender: "F",
					school_esis_id: "ESIS001",
					student_group_id: "G1",
					schooldb: "UB_SCHOOL_DB",
					schoolname: "Нийслэлийн 1-р сургууль",
					studentgroupname: "12A",
					seatid: 1,
					seat_number: "A1",
					rownum: 1,
					colnum: 1,
					exam_registration_id: 5001,
					status_code: 1,
					status_text: "Registered",
				},
				{
					id: 2,
					stu_id: 1002,
					examinee_number: "31251962",
					first_name: "Бат",
					last_name: "Эрдэнэ",
					register_number: "ФД07292730",
					gender: "M",
					school_esis_id: "ESIS002",
					student_group_id: "G1",
					schooldb: null,
					schoolname: null,
					studentgroupname: "12A",
					seatid: 2,
					seat_number: "A2",
					rownum: 1,
					colnum: 2,
					exam_registration_id: null,
					status_code: 0,
					status_text: "Pending",
				},
			],
		},
		{
			exam_room_id: 2,
			room_number: "201",
			num_of_pc: 30,
			assigned_seats: 1,
			total_students: 1,
			students: [
				{
					id: 3,
					stu_id: 1003,
					examinee_number: "31251963",
					first_name: "Сарангэрэл",
					last_name: "Мөнхбат",
					register_number: "ФД07292731",
					gender: null,
					school_esis_id: "ESIS003",
					student_group_id: "G2",
					schooldb: "UB_SCHOOL_DB",
					schoolname: "Нийслэлийн 23-р сургууль",
					studentgroupname: "11B",
					seatid: 5,
					seat_number: "B1",
					rownum: 2,
					colnum: 1,
					exam_registration_id: 5003,
					status_code: 1,
					status_text: "Registered",
				},
			],
		},
	],
};
